myproject/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("survey/", include("survey.urls")),  # Ensure this is present
]

survey/urls.py
from . import views
from django.contrib import admin
from django.urls import include, path

app_name = "survey"
urlpatterns = [
    path("", views.index, name="survey_home"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

survey/models.py
from django.db import models
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    class Meta:
        db_table = "survey_question"

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0) 

    def __str__(self):
        return self.choice_text

survey/views.py
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from .models import Question


def index(request):
    questions = Question.objects.all()
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    template = loader.get_template("survey/index.html")
    context = {"latest_question_list": latest_question_list}
    return render(request, 'survey/index.html', {'questions': questions})


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "survey/detail.html", {"question": question})


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

survey/templates/survey/detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'survey/style.css' %}">
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul class="choices-list">
        {% for choice in question.choice_set.all %}
            <li class="choice-item">{{ choice.choice_text }} (Votes: {{ choice.votes }})</li>
        {% endfor %}
    </ul>
</body>
</html>

survey/templates/survey/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% load static %}
<link rel="stylesheet" href="{% static 'survey/style.css' %}">
</head>
<body>
    <h1>Developer Survey Questions</h1>
    <div class="question-container">
        {% for question in questions %}
        <div class="question-container">
            <p class="question-text">
                <h3 href="{% url 'survey:detail' question.id %}">{{ question.question_text }}</h3>
                <textarea name="" id="">Type your response here</textarea>
            </p>
        </div>
    {% endfor %}
    </div>
    <button type="submit">Submit your responses</button>
</body>
</html>